-- BioLife CRM — local development seed.
--
-- Intentionally contains NO user accounts and NO operational data (leads,
-- companies, tasks). Production and local dev both provision real accounts
-- through Supabase Auth (Dashboard locally: http://127.0.0.1:54323/project/default/auth/users,
-- or Authentication → Users on the hosted project) so no password is ever
-- committed to this repository.
--
-- Structural/reference data (pipeline_stages) is seeded by the initial
-- schema migration, not here, since it is part of the application's
-- configuration rather than operational data.
--
-- To develop locally:
--   1. `npm run db:start`
--   2. Open Supabase Studio (URL printed by db:start) → Authentication → Users → Add user
--   3. Set User Metadata to {"full_name": "Your Name", "role": "admin"} (or
--      "growth_operations" / "read_only") so the handle_new_user() trigger
--      provisions the matching profiles row.
